#!/bin/bash

WERCKER_SCALR_API_TIMESTAMP=$(date -u "+%Y-%m-%dT%H:%M:%SZ")
WERCKER_SCALR_API_VALUE="$WERCKER_SCALR_API_ACTION:$WERCKER_SCALR_API_ACCESS_KEY_ID:$WERCKER_SCALR_API_TIMESTAMP"
WERCKER_SCALR_API_RESULT=$(printf $WERCKER_SCALR_API_VALUE | openssl dgst -sha256 -binary -hmac $WERCKER_SCALR_API_API_KEY)
WERCKER_SCALR_API_SIGNATURE=$(printf $WERCKER_SCALR_API_RESULT | openssl base64 -e -A)

WERCKER_SCALR_API_PARAMS="Action=${WERCKER_SCALR_API_ACTION}&KeyID=${WERCKER_SCALR_API_KEY_ID}&AuthVersion=3&Version=${WERCKER_SCALR_API_API_VERSION}"${WERCKER_SCALR_API_PARAMS}

curl -s -G ${WERCKER_SCALR_API_ENDPOINT}?${WERCKER_SCALR_API_PARAMS} --data-urlencode "TimeStamp=$WERCKER_SCALR_API_TIMESTAMP" --data-urlencode "Signature=$WERCKER_SCALR_API_SIGNATURE"
